spring.application.name=hakathon
spring.datasource.url=jdbc:mysql://localhost:3306/hakathon_web_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Duong170226@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.web.error.include-stacktrace=never